name: "kafka-ingest-source"
tenant: "public"
namespace: "default"
topicName: "persistent://public/default/from-kafka-topic"
archive: "builtin://kafka"

configs:
  # Kafka broker address
  bootstrapServers: "kafka:9092"
  # Consumer group for offset management
  groupId: "example-group"
  # Kafka topic to consume
  topic: "my-kafka-topic"
  # Additional consumer settings (optional)
  sessionTimeoutMs: 10000
  autoCommitEnabled: false
  autoCommitIntervalMs: 1000
