tenant: acme
namespace: ingest

connectors:
  kinesis-input:
    source: true
    image: streamnative/pulsar-io-kinesis:2.10.0
    configRef: kinesis-source-config
    output: raw-kinesis-events
  kafka-input:
    source: true
    image: streamnative/pulsar-io-kafka:2.10.0
    configRef: kafka-source-config
    output: raw-kafka-events
  azure-eventhub-input:
    source: true
    image: streamnative/pulsar-io-azure-eventhub:2.10.0
    configRef: azure-eventhub-source-config
    output: raw-azure-events
  rabbitmq-input:
    source: true
    image: streamnative/pulsar-io-rabbitmq:2.10.0
    configRef: rabbitmq-source-config
    output: raw-rabbitmq-events
  http-input:
    source: true
    image: streamnative/pulsar-io-http:2.10.0 # Placeholder, typically a sink
    configRef: http-source-config
    output: raw-http-events
  grpc-input:
    source: true
    image: acme/grpc-source-connector:0.1.0
    configRef: grpc-source-config
    output: raw-grpc-events
  pulsar-source-input:
    source: true
    image: acme/pulsar-source-connector:0.1.0 # Assuming custom connector from /connectors/pulsar-source
    configRef: pulsar-source-config
    output: raw-pulsar-events

functions:
  user-profile-translator:
    image: ghcr.io/acme/translators:0.1.0
    className: com.example.pulsar.functions.cmf.UserProfileTranslator
    inputs:
      - raw-azure-events
      - raw-pulsar-events
    output: common-events
  order-record-translator:
    image: ghcr.io/acme/translators:0.1.0
    className: com.example.pulsar.functions.cmf.OrderRecordTranslator
    inputs:
      - raw-grpc-events
      - raw-rabbitmq-events
    output: common-events
  inventory-update-translator:
    image: ghcr.io/acme/translators:0.1.0
    className: com.example.pulsar.functions.cmf.InventoryUpdateTranslator
    input: raw-http-events # Single input
    output: common-events
  payment-notice-translator:
    image: ghcr.io/acme/translators:0.1.0
    className: com.example.pulsar.functions.cmf.PaymentNoticeTranslator
    input: raw-kafka-events # Single input
    output: common-events
  shipment-status-translator:
    image: ghcr.io/acme/translators:0.1.0
    className: com.example.pulsar.functions.cmf.ShipmentStatusTranslator
    input: raw-kinesis-events # Single input
    output: common-events
  event-type-splitter:
    image: ghcr.io/acme/splitter:0.1.0
    className: com.example.pulsar.filterer.EventTypeSplitter
    input: common-events
    # Outputs are dynamic for this function, so not listed here.
