name: "rabbitmq-ingest-source"
tenant: "public"
namespace: "default"
topicName: "persistent://public/default/from-rabbitmq-topic"
archive: "builtin://rabbitmq"

configs:
  host: "rabbitmq"
  port: 5672
  virtualHost: "/"      
  username: "user"
  password: "password"
  queueName: "my-queue"
  connectionName: "rabbitmq-connection"
  # Optional advanced settings (using default values here)
  requestedChannelMax: 0
  requestedFrameMax: 0
  connectionTimeout: 60000
  handshakeTimeout: 10000
  requestedHeartbeat: 60
  prefetchCount: 0
  prefetchGlobal: false
  passive: false
