# Pulsar AMQP 1.0 Source Configuration for Azure Event Hubs

# Connection properties
connection:
  host: "<your-eventhubs-namespace-fqdn>" # e.g., your-namespace.servicebus.windows.net
  port: 5671 # Default AMQP TLS port
  # Optional: specify if non-TLS is used (not recommended for Event Hubs)
  # port: 5672 # Default AMQP non-TLS port
  tlsEnabled: true
  # Optional: for TLS client certificate authentication (if applicable)
  # tlsTrustCertsFilePath: "/path/to/ca.pem"
  # tlsKeyFilePath: "/path/to/client-key.pem"
  # tlsCertificateFilePath: "/path/to/client-cert.pem"
  # tlsHostnameVerificationEnable: true

# Authentication: SASL PLAIN is commonly used with Event Hubs Connection Strings
# The username is often "$ConnectionString" or a specific Shared Access Policy name.
# The password is the full Event Hubs Connection String or the Primary/Secondary Key of the SAS policy.
authentication:
  saslMechanism: "PLAIN" # Or other mechanisms like EXTERNAL for client certs, or Azure-specific if available
  username: "$ConnectionString" # Or your SAS Policy Name like "RootManageSharedAccessKey"
  password: "<your-eventhubs-connection-string-or-sas-key>"

# Source configuration
source:
  # The AMQP address for the source link, typically the Event Hub name.
  address: "<your-eventhub-name>"
  # Optional: Consumer group (subscriber name for AMQP)
  # If Event Hubs maps AMQP consumer groups to its own consumer groups, set this.
  # Otherwise, Event Hubs might manage consumer offsets per link based on link name or other properties.
  # consumerGroupId: "$Default" # Or your specific consumer group

# Optional: AMQP Link properties (e.g., prefetch/credit)
# link:
  # credit: 1000 # Number of messages to prefetch

# Pulsar specific properties
# topic: "persistent://public/default/eventhub-amqp-input-topic" # Can also be set here if not in connector.yaml
