apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: Prometheus # Link to Prometheus for traceID
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: '$${__value.raw}' # Important: $$ to escape $ for shell heredoc
    editable: true
