version: "3.8"

services:
    pulsar:
        image: apachepulsar/pulsar:3.1.1
        container_name: pulsar
        command: ["pulsar/bin/pulsar", standalone]
        environment:
            - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g
            - PULSAR_PREFIX_brokerPrometheusMetricsPort=8081
        ports:
            - "6650:6650"
            - "8080:8080"
            - "8081:8081"
        volumes:
            - pulsar-data:/pulsar/data
            - pulsar-conf:/pulsar/conf
    localstack:
        image: localstack/localstack:latest
        container_name: localstack
        ports:
            - "4566:4566" #edge service
        environment:
            - SERVICES=kinesis,sts,iam
            - PERSISTENCE=1
        volumes:
            - localstack-data:/var/lib/localstack

volumes:
    pulsar-data:
    pulsar-conf:
    localstack-data:
    