name: "netty-ingest-source"
tenant: "public"
namespace: "default"
topicName: "persistent://public/default/netty-topic"
archive: "builtin://netty"

configs:
  # Use HTTP protocol for incoming messages
  type: "http"
  host: "0.0.0.0"
  port: 10999
  numberOfThreads: 1
